CRED_TYPE_GENERIC = 1
CRED_PERSIST_LOCAL_MACHINE = 2
CREDUI_FLAGS_ALWAYS_SHOW_UI = 0x80
CREDUI_FLAGS_GENERIC_CREDENTIALS = 0x40000
CREDUI_FLAGS_SHOW_SAVE_CHECK_BOX = 0x2
ERROR_NOT_FOUND = 1168
ERROR_CANCELLED = 1223
